### PR TITLE
fix watch attribute change

### PR DESCRIPTION
**Pull request by salexch**
fix for mutation and old browsers watch for attribute mutations

### CODE REVIEW

**Comment by salexch** [comment]
anybody?

**Comment by Duder-onomy** [comment]
The tests have failed. 
I will pull down your changes and check locally then get back to you. 
Will probably also need to check in another TV app to ensure still functioning as expected.
Gimme a few. Need to push a staging build on another proj.

**Comment by salexch** [comment]
thank you!

**Comment by Duder-onomy** [comment]
@salexch Can you remake your pull request. There is a undefined variable. I cannot infer from the code where it should be coming from. 

Line number 287 is preventing the tests from running.  Can you rename the var 'elem' and ensure it is being defined somewhere?

Otherwise, looks pretty good. Thanks for the PR.

**Comment by salexch** [comment]
I think there is a problem with package.json..
locally I changed dependencies to
    "bower": "*",
    "mocha": "^2.3.4",
    "mocha-phantomjs": "^4.0.2",
    "phantomjs": "^1.9.19",

anyway, npm test works and I pass the tests

**Comment by pajtai** [comment]
Think you're right about a package.json error. It looks like [the error](https://travis-ci.org/Solid-Interactive/magic-focus-finder/jobs/102784941) is:

    npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer mocha-phantomjs@3.6.0 wants phantomjs@1.9.1 - 1.9.7-15

Think if you bump mocha-phantomjs it should be good. Looks like phantomjs is at 1.9.19 but mocha-phantomjs@3.6.0 only accepts upt to 1.9.15.

**Comment by salexch** [comment]
why you are not merging?

**Comment by Duder-onomy** [comment]
Thanks for the PR Alex. I hope you find this lib useful on your other TV apps. 

I am going to refactor the pull request and add some tests. Then we will make a new version. You should pull that version.

Greg

**Comment by salexch** [comment]
Hi, the watch attribute mutation introduced a bug.. it could be seen on relative small lists ~15 items.
hiding showing item in the list throws a lot of events on observer, it makes browser freeze..

meanwhile I made a temporary fix

         if((window.MutationObserver || window.WebKitMutationObserver) && internal.config.useNativeMutationObserver) {
            var delay_timer = null;
            internal.domObserver = new MutationObserver(function(mutations) {
                clearTimeout(delay_timer);
                delay_timer = setTimeout(function() {
                    refresh();
                }, 100);
            });

            internal.domObserver.observe(internal.config.container, {
                childList: true,
                subtree : true,
                attributes: true,
                attributeOldValue: true,
                attributeFilter: internal.watchedAttributes
            });
        }

**Comment by Duder-onomy** [comment]
Hi Alex, 
If you are calling refresh every 100ms then there is no reason to even use mutation observers. 

Also, how often are you changing attributes? in all of the TV's apps we have done with this lib, we have never needed an attribute mutation observer.

Can you tell us the use case? What you are trying to accomplish with the attribute observation? I bet there is a better faster way.

Greg

**Comment by salexch** [comment]
I don't call refresh every 100ms, only when observer callback is invoked, and if it invoked to often I reset the timer.. to wait for dom relaxation..

any way, my use case:

the app in one of its template has attribute focus-overrides, the business logic requires me to set different values for this attribute, sure I can do it brute force or using magicfocus.refresh in the view, but I think it should be native for this plugin.. it's the natural way..

**Comment by Duder-onomy** [comment]
Hi Alex, 

I think I have an idea to make this better. the movement logic should just check the  'focus-overrides' attribute each time instead of caching it. I think this will work better than mutation observer for attributes. I will work on this tonight.

**Comment by salexch** [comment]
Thank you! Too bad samsung and others don't have this or similar plugin in
their API.. it should be their concern.. its basic for TV.. its like in
mobile you had to write touch events yourself..

Any way I will try to check more deeply what happes to attribute mutation
event in my use case. For now you right, its better to check those
attributes on every move.. sorry I introduced this bug..

**Comment by Duder-onomy** [comment]
Hi Alex, 
I am working on this right now. Expect a new release in about....2 hours.
Greg

**Comment by Duder-onomy** [comment]
Hi Alex, 

New version is published,  2.11.0
This one should respect changes to the currently focused elements direction overrides on every movement. 

Please let us know if this helps you.

**Pull request merged**
